services:

  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:${POSTGRESQL_VERSION}
    networks:
      - temporal-network
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  temporal:
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/auto-setup:${TEMPORAL_VERSION}
    networks:
      - temporal-network
    ports:
      - "7233:7233"
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:${TEMPORAL_ADMINTOOLS_VERSION}
    networks:
      - temporal-network
    stdin_open: true
    tty: true

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    networks:
      - temporal-network
    ports:
      - "8080:8080"

  postgres-order-outbox:
    image: postgres:16
    container_name: postgres-order-outbox
    environment:
      POSTGRES_USER: order_outbox
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: order_outbox_db
    ports:
      - "5431:5432"
    networks:
      - temporal-network

  postgres-order:
    image: postgres:16
    container_name: postgres-order
    environment:
      POSTGRES_USER: order
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"
    networks:
      - temporal-network

  postgres-payment:
    image: postgres:16
    container_name: postgres-payment
    environment:
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: payment_db
    ports:
      - "5434:5432"
    networks:
      - temporal-network

  postgres-shipping:
    image: postgres:16
    container_name: postgres-shipping
    environment:
      POSTGRES_USER: shipping
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: shipping_db
    ports:
      - "5435:5432"
    networks:
      - temporal-network


networks:
  temporal-network:



