
server:
  port: 8083

spring:
  application:
    name: shipping-service

  datasource:
    url: jdbc:postgresql://localhost:5435/shipping_db
    username: shipping
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.yaml

  temporal:
    namespace: order-ns
    connection:
      target: 127.0.0.1:7233
    workers-auto-discovery:
      packages: ru.boraldan.shippingservice